version: '3.4'

volumes:
  datafiles:

services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CurrencyRates
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  currencyinfogetter:
    image: ldubsterl/exchange_rate_getter
    depends_on: 
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: CurrencyInfoGetter/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
    ports:
      - "25565:8080"
      - "25566:8081"