version: '3.4'

volumes:
  datafiles:

services:
  database:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CurrencyRates

  currencyinfogetter:
    image: ldubsterl/currencyinfogetter
    depends_on: 
      - database
    build:
      context: .
      dockerfile: CurrencyInfoGetter/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
    ports:
      - "25565:8080"
      - "25566:8081"